# Generated by Django 3.0.8 on 2020-11-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('author', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('category', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('dt', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
